//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkRequestConsole.com.asiacell.smsclientv2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.websms/", ConfigurationName="com.asiacell.smsclientv2.AsiacellWebSMSService")]
    public interface AsiacellWebSMSService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BulkRequestConsole.com.asiacell.smsclientv2.ReceiveResponse Receive(BulkRequestConsole.com.asiacell.smsclientv2.Receive request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.ReceiveResponse> ReceiveAsync(BulkRequestConsole.com.asiacell.smsclientv2.Receive request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BulkRequestConsole.com.asiacell.smsclientv2.RefreshResponse Refresh(BulkRequestConsole.com.asiacell.smsclientv2.Refresh request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.RefreshResponse> RefreshAsync(BulkRequestConsole.com.asiacell.smsclientv2.Refresh request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BulkRequestConsole.com.asiacell.smsclientv2.validatePushResponse validatePush(BulkRequestConsole.com.asiacell.smsclientv2.validatePush request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.validatePushResponse> validatePushAsync(BulkRequestConsole.com.asiacell.smsclientv2.validatePush request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlResponse validatePushUrl(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlResponse> validatePushUrlAsync(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BulkRequestConsole.com.asiacell.smsclientv2.SendResponse Send(BulkRequestConsole.com.asiacell.smsclientv2.Send request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.SendResponse> SendAsync(BulkRequestConsole.com.asiacell.smsclientv2.Send request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class receivedReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestidField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string senderField;
        
        private string receiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
                this.RaisePropertyChanged("requestid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("receiver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionidField;
        
        private string requestIdField;
        
        private string clientIdField;
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string transactionid {
            get {
                return this.transactionidField;
            }
            set {
                this.transactionidField = value;
                this.RaisePropertyChanged("transactionid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("resultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionidField;
        
        private string requestidField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string clientidField;
        
        private string senderField;
        
        private string receiverField;
        
        private int languageField;
        
        private bool languageFieldSpecified;
        
        private string messageTextField;
        
        private int smscidField;
        
        private bool smscidFieldSpecified;
        
        private string vasServiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string transactionid {
            get {
                return this.transactionidField;
            }
            set {
                this.transactionidField = value;
                this.RaisePropertyChanged("transactionid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
                this.RaisePropertyChanged("requestid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string clientid {
            get {
                return this.clientidField;
            }
            set {
                this.clientidField = value;
                this.RaisePropertyChanged("clientid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
                this.RaisePropertyChanged("languageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("messageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int smscid {
            get {
                return this.smscidField;
            }
            set {
                this.smscidField = value;
                this.RaisePropertyChanged("smscid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smscidSpecified {
            get {
                return this.smscidFieldSpecified;
            }
            set {
                this.smscidFieldSpecified = value;
                this.RaisePropertyChanged("smscidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string vasService {
            get {
                return this.vasServiceField;
            }
            set {
                this.vasServiceField = value;
                this.RaisePropertyChanged("vasService");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class validatePushUrlReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class validateResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("resultDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class validateReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string shortcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string shortcode {
            get {
                return this.shortcodeField;
            }
            set {
                this.shortcodeField = value;
                this.RaisePropertyChanged("shortcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class refreshResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("resultDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class refreshReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.websms/")]
    public partial class receivedResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionidField;
        
        private string requestIdField;
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        private string sendermisisdnField;
        
        private string receivermsisdnField;
        
        private string vas_serviceField;
        
        private string messageField;
        
        private System.DateTime send_onField;
        
        private bool send_onFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private int langField;
        
        private bool langFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string transactionid {
            get {
                return this.transactionidField;
            }
            set {
                this.transactionidField = value;
                this.RaisePropertyChanged("transactionid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("resultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sendermisisdn {
            get {
                return this.sendermisisdnField;
            }
            set {
                this.sendermisisdnField = value;
                this.RaisePropertyChanged("sendermisisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string receivermsisdn {
            get {
                return this.receivermsisdnField;
            }
            set {
                this.receivermsisdnField = value;
                this.RaisePropertyChanged("receivermsisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vas_service {
            get {
                return this.vas_serviceField;
            }
            set {
                this.vas_serviceField = value;
                this.RaisePropertyChanged("vas_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime send_on {
            get {
                return this.send_onField;
            }
            set {
                this.send_onField = value;
                this.RaisePropertyChanged("send_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool send_onSpecified {
            get {
                return this.send_onFieldSpecified;
            }
            set {
                this.send_onFieldSpecified = value;
                this.RaisePropertyChanged("send_onSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool langSpecified {
            get {
                return this.langFieldSpecified;
            }
            set {
                this.langFieldSpecified = value;
                this.RaisePropertyChanged("langSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Receive", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class Receive {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.receivedReq Request;
        
        public Receive() {
        }
        
        public Receive(BulkRequestConsole.com.asiacell.smsclientv2.receivedReq Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveResponse", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class ReceiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.receivedResp @return;
        
        public ReceiveResponse() {
        }
        
        public ReceiveResponse(BulkRequestConsole.com.asiacell.smsclientv2.receivedResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Refresh", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class Refresh {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.refreshReq Request;
        
        public Refresh() {
        }
        
        public Refresh(BulkRequestConsole.com.asiacell.smsclientv2.refreshReq Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshResponse", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class RefreshResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.refreshResp @return;
        
        public RefreshResponse() {
        }
        
        public RefreshResponse(BulkRequestConsole.com.asiacell.smsclientv2.refreshResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatePush", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class validatePush {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.validateReq Request;
        
        public validatePush() {
        }
        
        public validatePush(BulkRequestConsole.com.asiacell.smsclientv2.validateReq Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatePushResponse", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class validatePushResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.validateResp @return;
        
        public validatePushResponse() {
        }
        
        public validatePushResponse(BulkRequestConsole.com.asiacell.smsclientv2.validateResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatePushUrl", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class validatePushUrl {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlReq arg0;
        
        public validatePushUrl() {
        }
        
        public validatePushUrl(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlReq arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatePushUrlResponse", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class validatePushUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.validateResp @return;
        
        public validatePushUrlResponse() {
        }
        
        public validatePushUrlResponse(BulkRequestConsole.com.asiacell.smsclientv2.validateResp @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class Send {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.request Request;
        
        public Send() {
        }
        
        public Send(BulkRequestConsole.com.asiacell.smsclientv2.request Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendResponse", WrapperNamespace="http://services.websms/", IsWrapped=true)]
    public partial class SendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.websms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BulkRequestConsole.com.asiacell.smsclientv2.response @return;
        
        public SendResponse() {
        }
        
        public SendResponse(BulkRequestConsole.com.asiacell.smsclientv2.response @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsiacellWebSMSServiceChannel : BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsiacellWebSMSServiceClient : System.ServiceModel.ClientBase<BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService>, BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService {
        
        public AsiacellWebSMSServiceClient() {
        }
        
        public AsiacellWebSMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsiacellWebSMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsiacellWebSMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsiacellWebSMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BulkRequestConsole.com.asiacell.smsclientv2.ReceiveResponse BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.Receive(BulkRequestConsole.com.asiacell.smsclientv2.Receive request) {
            return base.Channel.Receive(request);
        }
        
        public BulkRequestConsole.com.asiacell.smsclientv2.receivedResp Receive(BulkRequestConsole.com.asiacell.smsclientv2.receivedReq Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.Receive inValue = new BulkRequestConsole.com.asiacell.smsclientv2.Receive();
            inValue.Request = Request;
            BulkRequestConsole.com.asiacell.smsclientv2.ReceiveResponse retVal = ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).Receive(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.ReceiveResponse> BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.ReceiveAsync(BulkRequestConsole.com.asiacell.smsclientv2.Receive request) {
            return base.Channel.ReceiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.ReceiveResponse> ReceiveAsync(BulkRequestConsole.com.asiacell.smsclientv2.receivedReq Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.Receive inValue = new BulkRequestConsole.com.asiacell.smsclientv2.Receive();
            inValue.Request = Request;
            return ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).ReceiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BulkRequestConsole.com.asiacell.smsclientv2.RefreshResponse BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.Refresh(BulkRequestConsole.com.asiacell.smsclientv2.Refresh request) {
            return base.Channel.Refresh(request);
        }
        
        public BulkRequestConsole.com.asiacell.smsclientv2.refreshResp Refresh(BulkRequestConsole.com.asiacell.smsclientv2.refreshReq Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.Refresh inValue = new BulkRequestConsole.com.asiacell.smsclientv2.Refresh();
            inValue.Request = Request;
            BulkRequestConsole.com.asiacell.smsclientv2.RefreshResponse retVal = ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).Refresh(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.RefreshResponse> BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.RefreshAsync(BulkRequestConsole.com.asiacell.smsclientv2.Refresh request) {
            return base.Channel.RefreshAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.RefreshResponse> RefreshAsync(BulkRequestConsole.com.asiacell.smsclientv2.refreshReq Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.Refresh inValue = new BulkRequestConsole.com.asiacell.smsclientv2.Refresh();
            inValue.Request = Request;
            return ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).RefreshAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BulkRequestConsole.com.asiacell.smsclientv2.validatePushResponse BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.validatePush(BulkRequestConsole.com.asiacell.smsclientv2.validatePush request) {
            return base.Channel.validatePush(request);
        }
        
        public BulkRequestConsole.com.asiacell.smsclientv2.validateResp validatePush(BulkRequestConsole.com.asiacell.smsclientv2.validateReq Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.validatePush inValue = new BulkRequestConsole.com.asiacell.smsclientv2.validatePush();
            inValue.Request = Request;
            BulkRequestConsole.com.asiacell.smsclientv2.validatePushResponse retVal = ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).validatePush(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.validatePushResponse> BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.validatePushAsync(BulkRequestConsole.com.asiacell.smsclientv2.validatePush request) {
            return base.Channel.validatePushAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.validatePushResponse> validatePushAsync(BulkRequestConsole.com.asiacell.smsclientv2.validateReq Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.validatePush inValue = new BulkRequestConsole.com.asiacell.smsclientv2.validatePush();
            inValue.Request = Request;
            return ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).validatePushAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlResponse BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.validatePushUrl(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl request) {
            return base.Channel.validatePushUrl(request);
        }
        
        public BulkRequestConsole.com.asiacell.smsclientv2.validateResp validatePushUrl(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlReq arg0) {
            BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl inValue = new BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl();
            inValue.arg0 = arg0;
            BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlResponse retVal = ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).validatePushUrl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlResponse> BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.validatePushUrlAsync(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl request) {
            return base.Channel.validatePushUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlResponse> validatePushUrlAsync(BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrlReq arg0) {
            BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl inValue = new BulkRequestConsole.com.asiacell.smsclientv2.validatePushUrl();
            inValue.arg0 = arg0;
            return ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).validatePushUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BulkRequestConsole.com.asiacell.smsclientv2.SendResponse BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.Send(BulkRequestConsole.com.asiacell.smsclientv2.Send request) {
            return base.Channel.Send(request);
        }
        
        public BulkRequestConsole.com.asiacell.smsclientv2.response Send(BulkRequestConsole.com.asiacell.smsclientv2.request Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.Send inValue = new BulkRequestConsole.com.asiacell.smsclientv2.Send();
            inValue.Request = Request;
            BulkRequestConsole.com.asiacell.smsclientv2.SendResponse retVal = ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).Send(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.SendResponse> BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService.SendAsync(BulkRequestConsole.com.asiacell.smsclientv2.Send request) {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkRequestConsole.com.asiacell.smsclientv2.SendResponse> SendAsync(BulkRequestConsole.com.asiacell.smsclientv2.request Request) {
            BulkRequestConsole.com.asiacell.smsclientv2.Send inValue = new BulkRequestConsole.com.asiacell.smsclientv2.Send();
            inValue.Request = Request;
            return ((BulkRequestConsole.com.asiacell.smsclientv2.AsiacellWebSMSService)(this)).SendAsync(inValue);
        }
    }
}
